import { configure } from "enzyme";
import { convertDate, sortByDate } from "../utils/dateUtil";
import Adapter from "@cfaester/enzyme-adapter-react-18";
import tripData from "../types/trips";

configure({ adapter: new Adapter() });

it("should return a formatted date string when given a valid date string", () => {
  const result = convertDate("2022-01-01");
  expect(result).toMatch(/\d{2}\/\d{2}\/\d{4}/);
});

// Returns a sorted array of tripData objects based on checkInDate.
it("should return a sorted array of tripData objects based on checkInDate", () => {
  const arrayData = [
    {
      heroImage: "image1.jpg",
      unitName: "Unit 1",
      unitStyleName: "Style 1",
      checkInDate: new Date("2022-01-01"),
    },
    {
      heroImage: "image2.jpg",
      unitName: "Unit 2",
      unitStyleName: "Style 2",
      checkInDate: new Date("2022-02-01"),
    },
    {
      heroImage: "image3.jpg",
      unitName: "Unit 3",
      unitStyleName: "Style 3",
      checkInDate: new Date("2022-03-01"),
    },
  ];

  const sortedArray = sortByDate(arrayData, true);

  expect(sortedArray).toEqual([
    {
      heroImage: "image1.jpg",
      unitName: "Unit 1",
      unitStyleName: "Style 1",
      checkInDate: new Date("2022-01-01"),
    },
    {
      heroImage: "image2.jpg",
      unitName: "Unit 2",
      unitStyleName: "Style 2",
      checkInDate: new Date("2022-02-01"),
    },
    {
      heroImage: "image3.jpg",
      unitName: "Unit 3",
      unitStyleName: "Style 3",
      checkInDate: new Date("2022-03-01"),
    },
  ]);
});

// Returns an empty array when passed an array with only undefined elements.
it("should return an empty array when passed an array with only undefined elements", () => {
  const arrayData: tripData[] = [undefined, undefined, undefined];

  const sortedArray = sortByDate(arrayData);

  expect(sortedArray).toEqual([]);
});
// Generated by CodiumAI

describe("sortByDate", () => {
  // should return a sorted array of tripData objects based on checkInDate
  it("should return a sorted array of tripData objects based on checkInDate", () => {
    const arrayData = [
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ];

    const sortedArray = sortByDate(arrayData, true);

    expect(sortedArray).toEqual([
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ]);
  });

  // should return an empty array when passed an empty array
  it("should return an empty array when passed an empty array", () => {
    const arrayData: tripData[] = [];

    const sortedArray = sortByDate(arrayData);

    expect(sortedArray).toEqual([]);
  });

  // should return a sorted array of tripData objects based on checkInDate
  it("should return a sorted array of tripData objects based on checkInDate", () => {
    const arrayData = [
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ];

    const sortedArray = sortByDate(arrayData, true);

    expect(sortedArray).toEqual([
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ]);
  });

  // should return an empty array when passed an array with only undefined elements
  it("should return an empty array when passed an array with only undefined elements", () => {
    const arrayData: tripData[] = [undefined, undefined, undefined];

    const sortedArray = sortByDate(arrayData);

    expect(sortedArray).toEqual([]);
  });

  // should return an empty array when passed an empty array
  it("should return an empty array when passed an empty array", () => {
    const arrayData: tripData[] = [];

    const sortedArray = sortByDate(arrayData);

    expect(sortedArray).toEqual([]);
  });

  // should sort an array of tripData objects in descending order by default
  it("should return a sorted array of tripData objects in descending order by default", () => {
    const arrayData = [
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ];

    const sortedArray = sortByDate(arrayData);

    expect(sortedArray).toEqual([
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
    ]);
  });

  // should sort an array of tripData objects in ascending order when passed the second argument as true
  it("should return a sorted array of tripData objects in ascending order when passed the second argument as true", () => {
    const arrayData = [
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ];

    const sortedArray = sortByDate(arrayData, true);

    expect(sortedArray).toEqual([
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ]);
  });

  // should return an array of tripData objects sorted by checkInDate in ascending order when passed the second argument as true
  it("should return an array of tripData objects sorted by checkInDate in ascending order when passed the second argument as true", () => {
    const arrayData = [
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ];

    const sortedArray = sortByDate(arrayData, true);

    expect(sortedArray).toEqual([
      {
        heroImage: "image1.jpg",
        unitName: "Unit 1",
        unitStyleName: "Style 1",
        checkInDate: new Date("2022-01-01"),
      },
      {
        heroImage: "image2.jpg",
        unitName: "Unit 2",
        unitStyleName: "Style 2",
        checkInDate: new Date("2022-02-01"),
      },
      {
        heroImage: "image3.jpg",
        unitName: "Unit 3",
        unitStyleName: "Style 3",
        checkInDate: new Date("2022-03-01"),
      },
    ]);
  });
});
